// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMH1hoOaHdJmv38mMpTAVrK7d3_iDb5es',
    appId: '1:737337961463:web:bb34f42019ec233d0cdcf2',
    messagingSenderId: '737337961463',
    projectId: 'mvvm-solid-principle',
    authDomain: 'mvvm-solid-principle.firebaseapp.com',
    storageBucket: 'mvvm-solid-principle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMUH41FAQFE6tsg13f5R_a3kroWtYXeA',
    appId: '1:737337961463:android:9f36aa88c1b2a3550cdcf2',
    messagingSenderId: '737337961463',
    projectId: 'mvvm-solid-principle',
    storageBucket: 'mvvm-solid-principle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57uo1M0fTBS5zCYcUCIaKHXy42JuYoqQ',
    appId: '1:737337961463:ios:5b5cb2a7fbb2279b0cdcf2',
    messagingSenderId: '737337961463',
    projectId: 'mvvm-solid-principle',
    storageBucket: 'mvvm-solid-principle.firebasestorage.app',
    iosBundleId: 'com.solid.principle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57uo1M0fTBS5zCYcUCIaKHXy42JuYoqQ',
    appId: '1:737337961463:ios:49e50af096d0572d0cdcf2',
    messagingSenderId: '737337961463',
    projectId: 'mvvm-solid-principle',
    storageBucket: 'mvvm-solid-principle.firebasestorage.app',
    iosBundleId: 'com.example.todoKh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMH1hoOaHdJmv38mMpTAVrK7d3_iDb5es',
    appId: '1:737337961463:web:34efeef20fb0e9f40cdcf2',
    messagingSenderId: '737337961463',
    projectId: 'mvvm-solid-principle',
    authDomain: 'mvvm-solid-principle.firebaseapp.com',
    storageBucket: 'mvvm-solid-principle.firebasestorage.app',
  );
}
