// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMuEyDMx3bslKqXR6DZ4JxJG6eHpxXbc',
    appId: '1:833090696026:web:e0bedf0ac43d0199817963',
    messagingSenderId: '833090696026',
    projectId: 'chanpenh-flutter-flavors',
    authDomain: 'chanpenh-flutter-flavors.firebaseapp.com',
    storageBucket: 'chanpenh-flutter-flavors.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc88vLEOP4IwwYZbkP7SzgOPRjIXLilaM',
    appId: '1:833090696026:android:1c7ad3c45614e809817963',
    messagingSenderId: '833090696026',
    projectId: 'chanpenh-flutter-flavors',
    storageBucket: 'chanpenh-flutter-flavors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC65qL-ZiOkvC04kTAGOJ9Duynqd31LLuI',
    appId: '1:833090696026:ios:f4d559620e3d7a3c817963',
    messagingSenderId: '833090696026',
    projectId: 'chanpenh-flutter-flavors',
    storageBucket: 'chanpenh-flutter-flavors.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlavors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC65qL-ZiOkvC04kTAGOJ9Duynqd31LLuI',
    appId: '1:833090696026:ios:f4d559620e3d7a3c817963',
    messagingSenderId: '833090696026',
    projectId: 'chanpenh-flutter-flavors',
    storageBucket: 'chanpenh-flutter-flavors.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlavors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSMuEyDMx3bslKqXR6DZ4JxJG6eHpxXbc',
    appId: '1:833090696026:web:5f87fa97993674f8817963',
    messagingSenderId: '833090696026',
    projectId: 'chanpenh-flutter-flavors',
    authDomain: 'chanpenh-flutter-flavors.firebaseapp.com',
    storageBucket: 'chanpenh-flutter-flavors.firebasestorage.app',
  );
}
